# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AnsCli < Formula
  desc "Command-line tool for the Agent Name Service (ANS) Registry"
  homepage "https://github.com/godaddy/ans-sdk-go"
  version "0.1.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/godaddy/ans-sdk-go/releases/download/v0.1.13/ans-cli_0.1.13_darwin_amd64.tar.gz"
      sha256 "5175e56a38fb12090755ad2a691404c78e09caed205950426198e37bfa0963a4"

      define_method(:install) do
        bin.install "ans-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/godaddy/ans-sdk-go/releases/download/v0.1.13/ans-cli_0.1.13_darwin_arm64.tar.gz"
      sha256 "e20f6400e307f4b014b7225447c1bedfc44e6f0d02cdb45ba75d9897f8152369"

      define_method(:install) do
        bin.install "ans-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/godaddy/ans-sdk-go/releases/download/v0.1.13/ans-cli_0.1.13_linux_amd64.tar.gz"
      sha256 "65bdd48afa13d95c614f0caedaf5a99a9ab177849d3dad41f7cb7976ac9800b2"
      define_method(:install) do
        bin.install "ans-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/godaddy/ans-sdk-go/releases/download/v0.1.13/ans-cli_0.1.13_linux_arm64.tar.gz"
      sha256 "8846154b0db6d7c8e504b82b739835a13e34748369d219ea304166ab79938330"
      define_method(:install) do
        bin.install "ans-cli"
      end
    end
  end

  test do
    system "#{bin}/ans-cli", "--version"
  end
end
