# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AnsCli < Formula
  desc "Command-line tool for the Agent Name Service (ANS) Registry"
  homepage "https://github.com/agentnameservice/ans-sdk-go"
  version "0.1.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentnameservice/ans-sdk-go/releases/download/v0.1.17/ans-cli_0.1.17_darwin_amd64.tar.gz"
      sha256 "5752a0d916b756ae1b94ffa1c983b4b3775a42314267cf4793af40396eb671e9"

      define_method(:install) do
        bin.install "ans-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentnameservice/ans-sdk-go/releases/download/v0.1.17/ans-cli_0.1.17_darwin_arm64.tar.gz"
      sha256 "202bffb4c046e21fe0f7a9db6cd1fa6b13aa1daaa3190437df3e78eeb299d026"

      define_method(:install) do
        bin.install "ans-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentnameservice/ans-sdk-go/releases/download/v0.1.17/ans-cli_0.1.17_linux_amd64.tar.gz"
      sha256 "197edb8921aad065cea972b005b82d8afa8b8cc4f6f4c5091949a597539e420f"
      define_method(:install) do
        bin.install "ans-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentnameservice/ans-sdk-go/releases/download/v0.1.17/ans-cli_0.1.17_linux_arm64.tar.gz"
      sha256 "e354314c94b2840751ca8e602c72e7cd0c85ea882a5c9871bf1ebe986e6dbc51"
      define_method(:install) do
        bin.install "ans-cli"
      end
    end
  end

  test do
    system "#{bin}/ans-cli", "--version"
  end
end
