# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AnsCli < Formula
  desc "Command-line tool for the Agent Name Service (ANS) Registry"
  homepage "https://github.com/godaddy/ans-sdk-go"
  version "0.1.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/godaddy/ans-sdk-go/releases/download/v0.1.16/ans-cli_0.1.16_darwin_amd64.tar.gz"
      sha256 "968de0260d2c494cb8a459bde250571c9070acfefbf204cf18e13ec683430959"

      define_method(:install) do
        bin.install "ans-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/godaddy/ans-sdk-go/releases/download/v0.1.16/ans-cli_0.1.16_darwin_arm64.tar.gz"
      sha256 "5f2d99143a71f59ace76f8d6ddea4be2b24d475f24cfc994c3666c7fb2f83dc2"

      define_method(:install) do
        bin.install "ans-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/godaddy/ans-sdk-go/releases/download/v0.1.16/ans-cli_0.1.16_linux_amd64.tar.gz"
      sha256 "2cd45e1657a9c34f4a13a6a136bf86e82ad527cf6ed02f636202332aa5c401d5"
      define_method(:install) do
        bin.install "ans-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/godaddy/ans-sdk-go/releases/download/v0.1.16/ans-cli_0.1.16_linux_arm64.tar.gz"
      sha256 "d8d7c25d6f207b282fcb66e87a51858f4d34e0bb5f18ec8ea64a22993ed107e0"
      define_method(:install) do
        bin.install "ans-cli"
      end
    end
  end

  test do
    system "#{bin}/ans-cli", "--version"
  end
end
